version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    target-branch: "dev/main"
    schedule:
      interval: daily
    labels:
      - dependencies
    assignees:
      - ForteScarlet
    open-pull-requests-limit: 10

    ignore:
      - dependency-name: 'io.ktor:*'
        version: '3.+'
      - dependency-name: 'io.ktor.plugin'
        version: '3.+'
      - dependency-name: 'love.forte.plugin.suspend-transform:*'
      - dependency-name: 'love.forte.plugin.suspend-transform'
      - dependency-name: 'love.forte.plugin.suspend-transform'
      - dependency-name: 'org.jetbrains.dokka:*'
