changelog:
  exclude:
    labels:
      - 'for-release'
      - 'ignore-in-release'
  categories:
    - title: '🔧 Bug Fix'
      labels:
        - 'bug'
    - title: '⚙️ 修补缺陷'
      labels:
        - '缺陷'
    - title: '🎉 新特性'
      labels:
        - '特性'
    - title: '✨ 优化'
      labels:
        - '优化'
    - title: '👀 其他变更'
      labels:
        - '*'
