blank_issues_enabled: true

contact_links:
  - name: 问题反馈
    url: https://github.com/simple-robot/simpler-robot/issues/new/choose
    about: simbot统一的问题反馈处

  - name: 社区
    url: https://github.com/orgs/simple-robot/discussions
    about: simbot的GitHub交流讨论区
