name: Test Branch
on:
  pull_request:
    branches:
      - dev/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IS_CI: true
  GRADLE_OPTS: "-Dfile.encoding=UTF-8"

jobs:
  build-test:
    name: Build and test
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'

      - name: Run All Tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: |
            assemble
            build
            allTests
            --info 
            --warning-mode all
#            --build-cache
#            -Porg.gradle.daemon=false
#            -Porg.gradle.jvmargs="-Xmx4g -Xms2g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8"
